language: c
env:
  global:
   # Encrypted COVERITY_SCAN_TOKEN
   - secure: "oH5404MJM4pbnZ/tbxhJi6zM99wngwUw6gtWhpvkht+ywpVIFdUWRWSPuDe/5pTzG1U8AUTp6eV9/aUGSIc9KzGyjb/5ULJZBvLrq6qmKaa9/7XeS6Xj6TTAul3cYIyg9CSi496FcBVmwRVwjMc563cCOPot4uQWeYRJ3xHLLzzLt7YvLJ+uxqj8unveXiEWTZU7KW5kud+VS57Bj8kXyARR5Pddnp7Wlh6GTM3HG+W5Qx12s+DWbxuVdfRVHp+JgjkNZihCHplOU67FzeXKjX8by08lrRopiVLFB7gDb6f6Uik8oACmrobt+mkyfmrvvr3OCyXtGMmOWdkTzXr+gmSiFSlVnadnNKoD0mD6JKx5uXYbZSm2TUtn2x2fA6wG2M0urXIgQuquDOIMh0FzC+1iG76OBKmUuxZPZLbbd0YmuIzzVQsnKa5JdRsm6JXzVJkX6A4f/zX0KHovwwsycc5toL+i0C+O4AE6CtPgMn8m+g8RQYfCcgCne97LAN+XLoHaeqerNQInXQeyB2pdrURZ0EN9fF5LjG6V5KXvpJ9PideKQjgFktsdp9SfVTKfWgnWUl1o3RkpZt0iN8CwLKqrh6nTQKL99PZI/VVFCPhs3gpeZ9i08Co2OUR/Y4LqivdtxYTrsNZtD0A6sZDvCv8byFfES9r1KmrNmK9KYsY="
matrix:
  include:
  - name: "Linux with clang"
    env:
    - CONFIGURE_OPTIONS=""
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-clang"
    compiler: clang
    os: linux
    dist: trusty
    sudo: required
    group: edge
  - name: "Linux with gcc"
    env:
    - CONFIGURE_OPTIONS=""
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc"
    compiler: gcc
    os: linux
    dist: trusty
    sudo: required
    group: edge
  - name: "Linux with gcc and wide character type (wchar_t) support"
    env:
    - CONFIGURE_OPTIONS="--enable-wide-character-type"
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc-wide-character-type"
    compiler: gcc
    os: linux
    dist: trusty
    sudo: required
    group: edge
  - name: "Linux with gcc without optimization"
    env:
    - CONFIGURE_OPTIONS="--enable-shared=no --enable-wide-character-type"
    - CFLAGS="--coverage -O0"
    - CPPFLAGS="-DOPTIMIZATION_DISABLED"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc-no-optimization"
    compiler: gcc
    os: linux
    dist: trusty
    sudo: required
    group: edge
  - name: "Linux with gcc and shared libraries"
    env:
    - CONFIGURE_OPTIONS=""
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc-shared"
    compiler: gcc
    os: linux
    dist: trusty
    sudo: required
    group: edge
  - name: "Linux with gcc, shared libraries and wide character type (wchar_t) support"
    env:
    - CONFIGURE_OPTIONS="--enable-wide-character-type"
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc-shared-wide-character-type"
    compiler: gcc
    os: linux
    dist: trusty
    sudo: required
    group: edge
  - name: "Linux with gcc and static executables support"
    env:
    - CONFIGURE_OPTIONS="--enable-static-executables"
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc-static-executables"
    compiler: gcc
    os: linux
    dist: trusty
    sudo: required
    group: edge
  - name: "MacOS with clang"
    env:
    - CONFIGURE_OPTIONS=""
    - TARGET="macos-clang"
    compiler: clang
    os: osx
    osx_image: xcode8.3
  - name: "MacOS with gcc"
    env:
    - CONFIGURE_OPTIONS=""
    - TARGET="macos-gcc"
    compiler: clang
    compiler: gcc
    os: osx
    osx_image: xcode8.3
  - name: "MacOS gcc and pkgbuild"
    env:
    - CONFIGURE_OPTIONS="--disable-dependency-tracking --prefix=/usr/local"
    - TARGET="macos-gcc-pkgbuild"
    compiler: clang
    compiler: gcc
    os: osx
    osx_image: xcode8.3
before_install:
  - if test ${TRAVIS_OS_NAME} = "linux"; then
      sudo apt-get update && sudo apt-mark hold oracle-java8-installer oracle-java9-installer postgresql-9.2 postgresql-9.3 postgresql-9.4 postgresql-9.5 postgresql-9.6 postgresql-client postgresql-client-common postgresql-common postgresql-contrib-9.2 postgresql-contrib-9.3 postgresql-contrib-9.4 postgresql-contrib-9.5 postgresql-contrib-9.6 postgresql-doc && sudo apt-get --fix-missing -o Dpkg::Options::="--force-confold" upgrade -y --allow-unauthenticated && sudo apt-get install -y autopoint;
    elif test ${TRAVIS_OS_NAME} = "osx"; then
      brew update && brew install gettext gnu-sed && brew link --force gettext;
    fi
  - if test ${TARGET} = "coverity"; then
      echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-;
    fi
install:
  - if test ${TRAVIS_OS_NAME} = "osx"; then
      export SED="/usr/local/bin/gsed";
    fi
  - ./synclibs.sh --use-head && ./autogen.sh
  - if test ${TARGET} = "linux-gcc-shared" || test ${TARGET} = "linux-gcc-shared-wide-character-type"; then
      ./configure > /dev/null && make > /dev/null && ./syncsharedlibs.sh --use-head;
    fi
  - if test -x "synctestdata.sh"; then
      ./synctestdata.sh;
    fi
script:
  - if test ${TRAVIS_OS_NAME} = "linux"; then
      export PATH=$(echo $PATH | tr ":" "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s/::/:/g");
    fi
  - if test ${TARGET} != "coverity"; then
      ./configure ${CONFIGURE_OPTIONS} && make > /dev/null && make check CHECK_WITH_STDERR=1;
      if test $? -ne 0 && test -f tests/test-suite.log; then
        cat tests/test-suite.log;
      fi;
      if test ${TARGET} = "macos-gcc-pkgbuild"; then
        VERSION=`sed '5!d; s/^ \[//;s/\],$//' configure.ac` &&
        make install DESTDIR=${PWD}/osx-pkg &&
        mkdir -p ${PWD}/osx-pkg/usr/share/doc/libfsapfs &&
        cp AUTHORS COPYING NEWS README ${PWD}/osx-pkg/usr/share/doc/libfsapfs &&
        pkgbuild --root osx-pkg --identifier com.github.libyal.libfsapfs --version ${VERSION} --ownership recommended ../libfsapfs-${VERSION}.pkg;
      fi
    fi
after_success:
  - if test ${TARGET} = "linux-gcc-no-optimization"; then
      curl -o codecov.sh -s https://codecov.io/bash && /bin/bash ./codecov.sh -n ${TARGET} -y .codecov.yml;
    fi
